FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY Prerender.sln ./
COPY src/ ./src/

RUN dotnet restore Prerender.sln
RUN dotnet publish src/Prerender.Server/Prerender.Server.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

ENV ASPNETCORE_URLS=http://0.0.0.0:3000

COPY --from=build /app/publish/ ./

EXPOSE 3000

ENTRYPOINT ["dotnet", "Prerender.Server.dll"]
